exemptions:
  - check: artifacthub_badge
    reason: this is a sample reason
  - check: governance
    reason: "testing <script onload=\"{console.log('hi')}\">html</script>"
  - check: adopters
    reason:
  - check: maintainers
    reason: ""
